server:
   port: 8762
   
spring:
  application:
     name: zuul
   
zuul:
  sensitiveHeaders: usuario, clave  
  routes:
#    google:
#      path: /google/**
#      url: https://www.google.com/
#    privado:
#      path: /privado/**
#      url: http://www.profesor-p.com  
#    local:
#      path: /local/**
#      url: http://localhost:8080/api      
#    url:
#      path: /url/**
#      url: http://url.com
    gftbank:
      path: /gftbanck/**  
#      serviceId: SPRINGCLOUDWEBTEST
      serviceId: gftbanck-restservice
      
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#  instance:
#      hostname: localhost
#      nonSecurePort: 8080